version = 1

test_patterns = ["**/*.spec.ts","**/*_test.py","**/*_tests.py","**/test_*.py"]


[[analyzers]]
[analyzers.meta]
plugins = ["react"]
environment = ["nodejs"]

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
